### ISSUE TITLE
requirements conflicting

### ISSUE THREAD

**Issue by zhaozilong2zl** [zzzzzyh111/NonExpert-Guided-Visual-UAV-Navigation-Gazebo#1]
appreciate for your execllent work and open source your work! it help a lot for the uav community!

but i have some trouble to reproduce your project, some packages in requirements.txt is conflict with each other, can you provide the python version that can correctly install all packages?

thanks for the great work again, looking forward to your reply!
![image](https://github.com/user-attachments/assets/90f37d06-a791-49ea-812a-b6057cf82e9c)

**Comment by zzzzzyh111** [comment]
My Python version is 3.8.18. 
Regarding your question, I generated the ```requirements.txt``` file using ```pip freeze > requirements.txt```, so I'm not exactly sure what specific conflicts arise when transferring it to other virtual environments. However, I can clarify that ```wandb``` is primarily used for monitoring training metrics remotely, and it’s not essential to prioritize its installation. I recommend installing ```torch``` first based on your environment’s version, and then install ```wandb``` afterward.

**Comment by zhaozilong2zl** [comment]
> My Python version is 3.8.18. Regarding your question, I generated the `requirements.txt` file using `pip freeze > requirements.txt`, so I'm not exactly sure what specific conflicts arise when transferring it to other virtual environments. However, I can clarify that `wandb` is primarily used for monitoring training metrics remotely, and it’s not essential to prioritize its installation. I recommend installing `torch` first based on your environment’s version, and then install `wandb` afterward.

thank you for the quick reply!!! i successfully config the virtual environment by pip install the missing package after the earlier stop of the installation for requirements.txt
